services:
  web:
    container_name: photo-app
    ports: []
    networks:
      - catalystdev-local
      - default

  nginx:
    profiles:
      - disabled

networks:
  catalystdev-local:
    external: true
