# Generated by Django 5.2.6 on 2026-05-02 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_standardpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_eyebrow',
            field=models.CharField(default='about', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_heading',
            field=models.TextField(default="I'm Michel Groch,\nA Professional Photographer\nLiving In Indonesia."),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_paragraph_one',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_paragraph_two',
            field=models.TextField(default='Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_eyebrow',
            field=models.CharField(default="So What's Next?", max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_heading',
            field=models.CharField(default='Are You Ready?', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_heading_emphasis',
            field=models.CharField(default="Let's Work!", max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_link',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_four_description',
            field=models.TextField(default='Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_four_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_four_name',
            field=models.CharField(default='Panthere', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_one_description',
            field=models.TextField(default='Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_one_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_one_name',
            field=models.CharField(default='Fanter Studio', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_three_description',
            field=models.TextField(default='Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_three_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_three_name',
            field=models.CharField(default='Motor Heads', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_two_description',
            field=models.TextField(default='Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_two_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partner_two_name',
            field=models.CharField(default='GendatGraphic', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners_heading',
            field=models.CharField(default='Partner', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners_intro',
            field=models.TextField(default='Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project_image_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project_image_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project_image_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project_image_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects_button_link',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects_button_text',
            field=models.CharField(default='view projects', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects_eyebrow',
            field=models.CharField(default='Projects', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects_heading',
            field=models.TextField(default='A Good Ending Is The Most Important'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects_paragraph_one',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects_paragraph_two',
            field=models.TextField(default='Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='signature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_client_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_client_job',
            field=models.CharField(default='Photographer', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_client_name',
            field=models.CharField(default='Tommy Rivers', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonial_quote',
            field=models.TextField(default='" I\'m very picky with whom I give my energy to. I prefer to reserve my time, intensity and spirit exclusively to those who reflect sincerity. "'),
        ),
    ]
