# Generated by Django 5.2.5 on 2026-05-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_portfolioindexpage_gallerypage_gallerypageimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='presentation_style',
            field=models.CharField(choices=[('default', 'Default'), ('grid', 'Grid (Standard)'), ('masonry', 'Masonry'), ('animate-scroll-1', 'Animate Scroll 1'), ('animate-scroll-3', 'Animate Scroll 3'), ('gallery-carousel-1', 'Gallery Carousel 1'), ('gallery-carousel-2', 'Gallery Carousel 2')], default='default', max_length=32),
        ),
    ]
