# Generated by Django 5.2.5 on 2026-05-02 21:06

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProofingGallery',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('client_name', models.CharField(max_length=255)),
                ('shoot_date', models.DateField()),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secure token for gallery access.')),
                ('is_locked', models.BooleanField(default=False, help_text='Lock selections once the client finalizes.')),
                ('download_link_high_res', models.URLField(blank=True, help_text='Link to final deliverables.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProofImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('proof_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('selected_by_client', models.BooleanField(default=False)),
                ('gallery', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_images', to='proofing.clientproofinggallery')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
