# Generated by Django 5.2.5 on 2026-05-03 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('partner_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('referral_source', models.CharField(blank=True, max_length=255)),
                ('instagram_handle', models.CharField(blank=True, max_length=255)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text')], default='email', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientproofinggallery',
            name='client_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientproofinggallery',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientproofinggallery',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientproofinggallery',
            name='invite_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clientproofinggallery',
            name='invoice_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientproofinggallery',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientproofinggallery',
            name='package_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientproofinggallery',
            name='proof_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproofinggallery',
            name='session_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('invited', 'Invited'), ('proofing', 'Proofing'), ('finalized', 'Finalized'), ('delivered', 'Delivered')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='clientproofinggallery',
            name='shoot_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clientproofinggallery',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientproofinggallery',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofing_galleries', to='proofing.client'),
        ),
    ]
